N: 4
attn_resolutions: []
backbone: ncspp_l_crm
beta1: 0.9
beta2: 0.999
beta_max: 2
beta_min: 0.01
bridge_type: gmax
c: 0.4
centered: true
ch_mult:
- 1
- 1
- 2
- 2
- 2
- 2
- 2
ema_decay: 0.999
embedding_type: fourier
k: 2.6
loss_type: mse
lr: 0.0002
max_epochs: 500
nf: 128
noise_tune: false
nolog: false
num_res_blocks: 2
offset: 1.0e-05
opt_type: AdamW
predictor: x0
sampling_type: sde_first_order
scale_by_sigma: false
sde: bridgegan
t_eps: 0.03
